//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetreiveUploadimage.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class upload
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
